---
site_name: "hpc@azure"
use_directory_urls: false
repo_url: "https://github.com/seareport/hpc-azure"

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
extra:
  version:
    provider: mike

nav:
  - Overview: index.md
  - Infra: infra.md
  - Provisioning: provisioning.md
  - Documentation: docs.md
  # - Installation: installation.md
  # - API: api.md

markdown_extensions:
  - "admonition"
  - "codehilite"
  - "pymdownx.tilde"
  - "pymdownx.details"
  - "pymdownx.superfences"
  - toc:
      permalink: true

watch:
  - "docs"

plugins:
  - search:
  - print-site:
      exclude:
        - "docs.md"
      
